import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "../lib/AntdRegistry";
import HeaderLayout from "../components/HeaderLayout";
import FooterLayout from "../components/FooterLayout";
import TanstackProvider from "@/providers/TanstackProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanstackProvider>
          <StyledComponentsRegistry>
            <HeaderLayout />
            <main className="flex min-h-screen flex-col items-center justify-between p-12">
              {children}
            </main>
            <FooterLayout />
          </StyledComponentsRegistry>
        </TanstackProvider>
        
      </body>
    </html>
  );
}
