import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "../lib/AntdRegistry";
import HeaderLayout from "../components/HeaderLayout";
import FooterLayout from "../components/FooterLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <HeaderLayout />
          <main className="flex min-h-screen flex-col items-center justify-between p-24">
            {children}
          </main>

          <FooterLayout />
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
